# WaterdogPE Config
#
# Map of servers that will be indexed after proxy starts.
# Server address must be in format address:port
# Public server address can be used to specify address that is used when connecting though
servers:
  lobby1:
    address: 192.168.0.50:19133
    public_address: pvp.waterdog.io:19133
  lobby2:
    address: 192.168.0.50:19134

# Configuration of listener:
# Priorities are used to define server joining priority.
# If player will be unable to connect to server, server under will be used.
# Host address must be in format address:port.
# Using forced hosts players can connect directly to server.
# If a player joins with a forced host, this will skip the join server detection and will directly
# move the player to the target server.
listener:
  motd: "§bWaterdog§3PE"
  priorities:
    - lobby1
  host: 0.0.0.0:19132
  max_players: 20
  forced_hosts:
    pvp.waterdog.io: pvp

# Simple permission map to assign player permissions.
# Player permissions should be list of strings player_name: ["permission", "permission1"]
permissions:
  alemiz003:
    - "waterdog.player.transfer"
    - "waterdog.player.list"
# List of default permissions applied to player.
permissions_default:
  - "waterdog.command.help"
  - "waterdog.command.info"

# If this is enabled, the default log level will be set to DEBUG, outputting all kinds of useful information for debugging
enable_debug: false
# Enable online mode to prevent unauthorized players to join.
online_mode: true
#If enabled, the proxy will be able to bind to an Ipv6 Address.
enable_ipv6: false
# Some server software may have problem with extra attributes in packets. You can disable it here.
use_login_extras: true
# Disable if you do not want ho handle query requests.
enable_query: true
# Forward original address in client data under 'Waterdog_IP' attribute.
ip_forward: false
# Replace spaces in player's username.
replace_username_spaces: true
# Use fast transfer option if possible. Proxy will catch TransferServer packet and
# will use fast transfer is any server matches by address.
prefer_fast_transfer: true
# Proxy needs to encode and decode only some packets. Enabling this option will allow the proxy to pass
# original payload without encoding or decoding it. To save performance enable fast codec.
use_fast_codec: true
# Proxy can inject its commands to handled AvailableCommandsPacket from downstream.
# Using this option players will be able to see proxy commands in command list if they have permission.
inject_proxy_commands: true
# Compression settings
# Compression level between downstream and proxy may be lower, depends on your private network configuration.
# Higher level = more CPU, less bandwidth usage.
# Set to 0 to no compression, 9 to highest compression ratio.
upstream_compression_level: 6
downstream_compression_level: 2
# Resource packs settings
# Enable resource packs
enable_packs: true
# Client must accept resource packs to join
force_apply_packs: false
# Enabling resource pack caching may save disk IO,
# but caching bigger packs may be more RAM intensive.
# You can set maximum pack size in MB to be cached.
pack_cache_size: 16
